const F=window.FESTIVAL;
const defaults={view:"quest",done:[],demo:false,strong:true,visual:true,large:false,reduce:false,onboarded:false,events:[]};
let state={...defaults,...JSON.parse(localStorage.getItem("hq")||"{}")},watch=null,demoTimer=null,position=null,mapInstance=null;
const $=s=>document.querySelector(s),save=()=>localStorage.setItem("hq",JSON.stringify(state)),cp=()=>F.checkpoints.find(x=>!state.done.includes(x.id)),xp=()=>F.checkpoints.filter(x=>state.done.includes(x.id)).reduce((a,x)=>a+x.xp,0);
function event(type,data={}){state.events.push({type,at:new Date().toISOString(),...data});state.events=state.events.slice(-100);save();if(window.HQBackend?.enabled)HQBackend.track(F.id,type,data)}
function vibrate(d){if(navigator.vibrate)navigator.vibrate(state.strong?[d,Math.round(d/2),d]:d)}
function dist(a,b,c,d){const R=6371e3,p=x=>x*Math.PI/180,A=Math.sin(p(c-a)/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(p(d-b)/2)**2;return 2*R*Math.atan2(Math.sqrt(A),Math.sqrt(1-A))}
function complete(x,method="proximity"){if(!x||state.done.includes(x.id))return;state.done.push(x.id);event("checkpoint_complete",{checkpoint:x.id,method});vibrate(220);save();render()}
function check(){const x=cp();if(!x||!position)return;const d=dist(position.lat,position.lon,x.lat,x.lon);if(d<35)return complete(x);vibrate(d<80?90:d<180?55:25);render(d)}
function gps(){if(!navigator.geolocation)return alert("Geolocation is not available.");clearInterval(demoTimer);state.demo=false;event("gps_start");watch=navigator.geolocation.watchPosition(p=>{position={lat:p.coords.latitude,lon:p.coords.longitude};check()},()=>alert("Location permission is required for live quest mode. You can use a checkpoint code instead."),{enableHighAccuracy:true,maximumAge:5000});save()}
function stopTracking(){if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;clearInterval(demoTimer);demoTimer=null}
function demo(){stopTracking();state.demo=true;event("demo_start");let d=480;demoTimer=setInterval(()=>{const x=cp();if(!x)return clearInterval(demoTimer);d-=55;if(d<=20){complete(x,"demo");d=480}else{position={lat:x.lat+d/111111,lon:x.lon};check()}},900);save();render(d)}
function verifyCode(){const x=cp();if(!x)return;const code=(prompt("Enter the checkpoint code shown at the installation:")||"").trim().toUpperCase();if(code===x.code.toUpperCase())complete(x,"code");else if(code)alert("That code does not match the current checkpoint.")}
function onboarding(){return `<section class="hero"><div class="eyebrow">Haptic Quest · Festival pilot</div><h1>Explore without<br>following a blue line.</h1><p>Haptic Quest uses vibration, visual clues and optional GPS proximity to turn a festival route into a discovery game.</p></section><section class="card"><h2>Before you start</h2><p>Keep awareness of traffic, bikes, crowds and festival instructions. Haptics are discovery cues — not safety or turn-by-turn navigation.</p><p class="muted">Live location is processed on this device in the MVP and is not uploaded.</p><button class="btn" onclick="acceptOnboarding()">I understand — start quest</button><button class="btn alt" onclick="demo()">Preview with Demo Walk</button></section>`}
function acceptOnboarding(){state.onboarded=true;event("onboarding_complete");save();render()}
function quest(distance){if(!state.onboarded&&!state.demo)return onboarding();const x=cp(),score=xp();return `<section class="hero"><div class="eyebrow">${F.name} · ${F.theme}</div><h1>Feel the<br>next light.</h1><p>Follow the pulse. Discover something you might otherwise walk past.</p></section><section class="card"><div class="row"><b>${score} ${F.currency}</b><span>${state.done.length}/${F.checkpoints.length} found</span></div><div class="progress"><i style="width:${Math.min(100,score/F.goal*100)}%"></i></div></section>${x?`<section class="card"><div class="eyebrow">Next signal · +${x.xp}</div><div class="pulse" aria-label="Haptic signal">◉</div><h2>${state.visual?x.clue:"Destination hidden"}</h2><p class="muted">${distance?Math.round(distance)+" m away":"Start GPS, Demo Walk, or use the installation code."}</p><button class="btn" onclick="gps()">Start live GPS</button><button class="btn alt" onclick="demo()">Demo walk</button><button class="btn ghost" onclick="verifyCode()">Enter checkpoint code</button></section>`:`<section class="card"><div class="reward">✦</div><h2>CONNECT complete</h2><p>You collected ${score} ${F.currency}. Your completion reward is unlocked.</p><div class="reward-code">HQ-${F.id.slice(-4).toUpperCase()}-${state.done.length}X</div><button class="btn" onclick="resetQuest()">Play again</button></section>`}<p class="disclaimer">Independent concept prototype — not an official GLOW application. Prototype checkpoint data must be organizer-validated before public deployment.</p>`}
function mapView(){return `<h1>Discovery map</h1><p class="muted">Approximate quest context. Haptics remain the primary discovery mechanic.</p><div id="realmap" class="realmap" aria-label="Festival quest map"></div><section class="card">${F.checkpoints.map((x,i)=>`<div class="checkpoint ${state.done.includes(x.id)?"done":""}"><b>${state.done.includes(x.id)?"✓":"○"} ${i+1}. ${state.done.includes(x.id)?x.name:"Mystery signal"}</b><br><span class="muted">${state.done.includes(x.id)?x.place:x.xp+" "+F.currency}</span></div>`).join("")}</section>`}
function initMap(){if(state.view!=="map"||!window.L)return;mapInstance=L.map("realmap",{zoomControl:true}).setView([F.center.lat,F.center.lon],15);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(mapInstance);const pts=F.checkpoints.map(x=>[x.lat,x.lon]);L.polyline(pts,{dashArray:"8 8"}).addTo(mapInstance);F.checkpoints.forEach((x,i)=>L.circleMarker([x.lat,x.lon],{radius:9}).addTo(mapInstance).bindPopup(state.done.includes(x.id)?`${i+1}. ${x.name}`:`${i+1}. Mystery signal`));mapInstance.fitBounds(pts,{padding:[25,25]})}
function rewards(){const s=xp();return `<h1>Light wallet</h1><section class="card"><div class="big">${s} ✦</div><p class="muted">Earn ${F.currency} by discovering festival experiences.</p></section><section class="card"><h2>Completion reward</h2><p>${state.done.length===F.checkpoints.length?"Unlocked — ready to redeem.":"Complete all "+F.checkpoints.length+" signals to unlock."}</p><div class="progress"><i style="width:${state.done.length/F.checkpoints.length*100}%"></i></div></section><section class="card"><h3>Pilot reward examples</h3><span class="pill">Sponsor drink</span><span class="pill">Digital badge</span><span class="pill">Merch draw</span><span class="pill">Hidden installation</span></section>`}
function access(){return `<h1>Access</h1><p class="muted">No information is available only through vibration. Choose the cues that work for you.</p><section class="card"><label class="toggle">Strong haptic pattern <input type="checkbox" data-k="strong" ${state.strong?"checked":""}></label><label class="toggle">Show visual clues <input type="checkbox" data-k="visual" ${state.visual?"checked":""}></label><label class="toggle">Large text <input type="checkbox" data-k="large" ${state.large?"checked":""}></label><label class="toggle">Reduce motion <input type="checkbox" data-k="reduce" ${state.reduce?"checked":""}></label><button class="btn alt" onclick="vibrate(120)">Test haptic</button></section>`}
function organizer(){const counts=state.events.reduce((a,e)=>(a[e.type]=(a[e.type]||0)+1,a),{});return `<div class="eyebrow">Organizer preview</div><h1>Pilot dashboard</h1><section class="card"><div class="metrics"><div><b>${counts.onboarding_complete||0}</b><small>starts</small></div><div><b>${counts.checkpoint_complete||0}</b><small>discoveries</small></div><div><b>${state.done.length}</b><small>unique stops</small></div></div><p class="muted">MVP analytics are stored locally only. Production analytics should aggregate anonymous events and avoid retaining raw movement histories.</p></section><section class="card"><h2>Quest configuration</h2>${F.checkpoints.map(x=>`<div class="checkpoint"><b>${x.name}</b><br><span class="muted">${x.xp} ${F.currency} · radius 35m · code ${x.code}</span></div>`).join("")}</section><section class="card"><h2>What the pilot measures</h2><span class="pill">Quest starts</span><span class="pill">Completion</span><span class="pill">Stops discovered</span><span class="pill">Reward redemption</span><span class="pill">Accessibility settings</span></section>`}
function render(distance){document.body.classList.toggle("large",state.large);document.body.classList.toggle("reduce-motion",state.reduce);if(mapInstance){mapInstance.remove();mapInstance=null}$("#app").innerHTML=state.view==="quest"?quest(distance):state.view==="map"?mapView():state.view==="rewards"?rewards():state.view==="access"?access():organizer();document.querySelectorAll("[data-k]").forEach(i=>i.onchange=()=>{state[i.dataset.k]=i.checked;event("accessibility_change",{setting:i.dataset.k,value:i.checked});save();render()});if(state.view==="map")setTimeout(initMap,0)}
function resetQuest(){stopTracking();state.done=[];position=null;event("quest_reset");save();render()}
document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;save();render()});render();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");